{{- if .Values.storageClassBackup.create -}}
{{- $fullName := include "elasticsearch.uname" . -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storageClassBackup.pvcName }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}"
    app: "{{ template "elasticsearch.uname" . }}"
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  annotations:
    esMajorVersion: "{{ include "elasticsearch.esMajorVersion" . }}"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: {{ .Values.storageClassBackup.storageClassName }}
{{- end -}}
