apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.storageClassName }}
provisioner: disk.csi.azure.com
parameters:
  skuName: {{ .Values.storageClass.storageClassSku }}
  resourceGroup: {{ .Values.storageClass.resourceGroup }}
reclaimPolicy: {{ .Values.storageClass.reclaimPolicy }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
