name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: none
  # branches:
  #   include:
  #     - main
  #     - feature/*

variables: 
  - template: templates/variables-global.yaml
  - name : azureServiceConnectionForAcr
    value: AZR-NCE-DEV1
  - name : azureServiceConnectionForTest
    value: AZR-NCE-TST
  - name : azureServiceConnectionForPre
    value: AZR-NCE-PRE
  - name : deployToDev
    value: true
  - name : deployToTest
    value: true
  - name : deployToPre
    value: true

stages:

- stage: 'dev'
  displayName: 'Deploy to Dev'
  condition: and(succeeded(), and(eq(variables.isPullRequest, false), eq(variables.deployToDev, true)))
  jobs:
  - deployment: Deploy
    pool:
      name: DEFRA-COMMON-ubuntu2204-SSV3
    variables:
      - template: templates/variables-elasticsearch-dev.yaml
    environment: dev 
    strategy:
      runOnce:
        deploy:
          steps:
            - template: steps-deploy-elasticsearch-helm-charts.yaml
              parameters:
                releaseName: "elasticsearch"
                armServiceConnection: AZR-NCE-DEV1

- stage: 'test'
  displayName: 'Deploy to test'
  dependsOn: dev
  condition: and(succeeded(), and(eq(variables.isPullRequest, false), eq(variables.deployToTest, true)))
  jobs:
  - deployment: Deploy
    pool:
      name: DEFRA-COMMON-ubuntu2204-SSV3
    variables:
      - template: templates/variables-elasticsearch-test.yaml
    environment: test 
    strategy:
      runOnce:
        deploy:
          steps:
            - template: steps-deploy-elasticsearch-helm-charts.yaml
              parameters:
                releaseName: "elasticsearch"
                armServiceConnection: AZR-NCE-TST

- stage: 'pre'
  displayName: 'Deploy to Pre Prod'
  dependsOn: test
  condition: and(succeeded(), and(eq(variables.isPullRequest, false), eq(variables.deployToPre, true)))
  jobs:
  - deployment: Deploy
    pool:
      name: DEFRA-COMMON-ubuntu2204-SSV5
    variables:
      - template: templates/variables-elasticsearch-pre.yaml
    environment: pre 
    strategy:
      runOnce:
        deploy:
          steps:
            - template: steps-deploy-elasticsearch-helm-charts.yaml
              parameters:
                releaseName: "elasticsearch"
                armServiceConnection: AZR-NCE-PRE