# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: cat README.md
  displayName: 'Run a one-line script'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'defra-sonarcloud'
    organization: 'defra'
    scannerMode: 'MSBuild'
    projectKey: 'DEFRA_ncea-infrastructure-core'
    projectName: 'ncea-infrastructure-core'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'