{{- if .Values.create_elasticsearch_pod }}
{{- $global := .Values.global | default dict }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.espvc.elasticsearchPvcName }}
spec:
  accessModes:
  - {{ $global.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.espvc.elasticsearchPvcSize }}
  storageClassName: {{ .Values.peSaFileshare.elasticsearchShareScName }}
{{- end}}