{{- if .Values.create_elasticsearch_pod }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.elasticsearch.name }}
  annotations:
    geonetwork-ncea.version: {{ .Chart.Version }}
  labels:
      geonetwork-ncea/app: {{ $.Values.elasticsearch.name }}
      geonetwork-ncea/siteName: {{ .Release.Name }}
spec:
  type: {{ .Values.esservice.type }}
  ports:
    - name: tcp
      port: {{ .Values.esservice.port }}
      targetPort: tcp
      protocol: TCP
  selector:
      geonetwork-ncea/app: {{ $.Values.elasticsearch.name }}
      geonetwork-ncea/siteName: {{ .Release.Name }}

{{- end}}