apiVersion: v1
kind: Service
metadata:
  name: {{ include "geonetwork.fullname" . }}
  annotations:
    geonetwork.version: {{ .Chart.Version }}
  labels:
{{ include "geonetwork.labels" . | indent 4 }}
spec:
  type: {{ .Values.geoservice.type }}
  ports:
    - port: {{ .Values.geoservice.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    geonetwork/app: {{ include "geonetwork.name" . }}
    geonetwork/siteName: {{ .Release.Name }}