apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ncea-search-dynamic-premium-zrs
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_ZRS
  resourceGroup: sndadpinfrg3401-ncea-search
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true